<?php
//file : app/config/constants.php

return [
    'UserRegister' => 'You have been registered sucesssfully.Please login to continue.',
    'EmailExist' => 'This Email already exist.',
    'Invalid' => 'Invalid Credentials',
    'ManagerRegister' => 'Registered Successfully.',
    'StudioRegister' => 'Registered Successfully.',
    'PasswordResetLink' => 'Your password reset link send on email. Please check your spam folder in case you dont find it in inbox.',
    'EmailNotExist' => 'Email Not Exist!',
    'ChangePassword' => 'Password Change Successfully.',
    'VerificationError' => 'Please Enter Correct Verification code!',
    'ChangePassword' => 'Password change successfully, please login to continue.',
    'AuthExpire' => 'Session expired! please login to continue.',
    'VerifyEmail' => 'Please Verify Your Email First.',
    'ProfileUpdate' => 'Profile updated successfully.',
    'SomethingWrong' => 'Something went wrong!',
    'ConnectionExist' => 'Connection already created.',
    'ManagementExist' => 'Management is already exists between the two users.',
    'InvalidId' => 'User id not found!',
    'ConnectionCreated' => 'Connection created.',
    'ManagementCreated' => 'Management created.',
    'RequestAlert' => 'Requested to connect with you.',
    'RequestAlertES' => 'Se le solicitó conectarse con usted.',
    'RequestAlertFR' => 'A demandé à se connecter avec vous.',
    'RequestAlertZH' => '請求與您聯繫',
    'Connected' => 'Connected',
    'Pending' => 'Pending',
    'NotConnected' => 'Not connected',
    'RequestUpdated' => 'Connection request updated successfully.',
    'RequestNotFound' => 'Connection request not found!',
    'TypeArray' => array('1' => 'Creative', '2' => 'Manager', '3' => 'Studio'),
    'PaginateArray' => array('1' => '50', '2' => '30', '3' => '20', '4' => '10'),
    'AdvanceRegister' => 'Advance Data Saved Successfully.',
    'ProjectRegister'=> 'Project Saved Successfully.',
    'MatchRecord' => 'No match record found!',
    'RequestManagmentAlert' => 'Requested to be your manager.',
    'RequestManagmentAlertES' => 'Requerido para ser su gerente.',
    'RequestManagmentAlertFR' => 'A demandé à être votre manager.',
    'RequestManagmentAlertZH' => '要求成為您的經理',
    'RequestClientAlert' => 'Requested to be added as your client.',
    'RequestClientAlertES' => 'Solicitado para ser agregado como su cliente.',
    'RequestClientAlertFR' => 'A demandé à être ajouté en tant que client.',
    'RequestClientAlertZH' => '請求添加為您的客戶',
    'Unauthenticate' => 'Unauthenticate',
    'Manager' => 'Manager',
    'Creative' => 'Creative',
    'Studio' => 'Studio',
    'RequestAccepted' => 'Connection Request Accepted.',
    'RequestRejected' => 'Connection Request Rejected.',
    'AddConnection' =>'Add Connection',
    'Request' =>'Request Management',
    'hasProfile' => 1 ,
    'RequestSend' =>'Request send successfully.',
    'projectDelete' =>'Project Delete Successfully',
    'projectDeleteError' =>'Only Project Creator has a right to delete project.',
    'RequestAlreadySend' => 'Request Already Send.',
    'RequestNotSend' =>'Project Owner Can not be added as Contributor.',
    'project' => 'project',
    'management' =>'management',
    'saveContact'=>'Thanks for contact us',
    'ChannelAdded' =>'Channel Added Successfully',
    'streamdelete' =>'Stream Deleted Successfully',
    'youtubeApi'=>'AIzaSyD3PK-P8sVLNNWYLgznu9qmDdn7cCU9jqQ',
    'spotifyId'=>'acae01c383cb456bb1de40228926bd46',
    'spotifyClient'=>'e568069b06a64885ab2db2708f9a051d',
    'ChannelNotAdded' => 'Channel already added',
    'connectionType' => 'connection',
    'managementType' => 'management',
    'managementRequestAccepted' => 'Management Request Accepted.',
    'contributorRequestAccepted' => 'Contributor Request Accepted.',
    'Projectscombinesuccessfully'=> 'Projects are combine successfully.',
    'Projectsnotcombine' => 'Projects can not be combine.',
    'PleaseSelecttwoprojects' => 'Please Select two projects',
    'PleaseSelectprojects' => 'Please Select projects',
    'limit' => 5
];
